name: Pre-Release Continuos Integration

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test-stage:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js 12.14.1
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12.14.1
#      - name: Get Node_Modules cache directory
#        id: npm-cache
#        run: |
#          echo "::set-output name=dir::$(npm config get cache)"
#      - uses: actions/cache@v2
#        with:
#          path: ${{ steps.npm-cache.outputs.dir }}
#          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-node-
#      - name: Install dependencies
#        run: yarn install
      - name: Run Test pre Build Image
        run: echo 'Done!'

  build-stage:
    if: github.event_name == 'push'
    needs: test-stage
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      - name: Set Repository Name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/}" >> $GITHUB_ENV
      - name: Set version image
        run: echo "GHCR_IMAGE_VERSION=${GITHUB_REF_NAME#*\/}" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ env.GHCR_IMAGE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        

  pre-release-stage:
    needs: test-stage
    if: ${{ (github.event.pull_request.merged == true && github.event.action == 'closed' && (startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/'))) }}
    name: Pre-Release 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ge GITHUB_HEAD_REF version
        run: echo ${{ env.GITHUB_HEAD_REF }}
      - name: Set tag version
        run: echo "CI_TAG_VERSION=${GITHUB_HEAD_REF#*\/}" >> $GITHUB_ENV
      - name: echo tag version
        run: echo $CI_TAG_VERSION
      - name: Setup Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
      - name: Set app version
        run: npm version ${{ env.CI_TAG_VERSION }} -m "Upgrade app version to ${{ env.CI_TAG_VERSION }}"
      - name: Push latest app version
        run: |
          git pull
          git push origin main
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.CI_TAG_VERSION }}',
              sha: context.sha
            })

  create-release-stage:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: pre-release-stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set tag version
        run: echo "GHCR_IMAGE_VERSION=${GITHUB_HEAD_REF#*\/}" >> $GITHUB_ENV
      - name: echo tag version
        run: echo $GHCR_IMAGE_VERSION
      - name: Create Release
        run: gh release create ${{ env.GHCR_IMAGE_VERSION }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}